/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS_H_RPCGEN
#define _NFS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct open_params {
	char *file;
	int flags;
	int mode;
};
typedef struct open_params open_params;

struct creat_params {
	char *file;
	int mode;
};
typedef struct creat_params creat_params;

struct lseek_params {
	int fd;
	int offset;
	int whence;
};
typedef struct lseek_params lseek_params;

struct write_params {
	int fd;
	struct {
		u_int bytes_len;
		char *bytes_val;
	} bytes;
};
typedef struct write_params write_params;

struct read_params {
	int fd;
	int max;
};
typedef struct read_params read_params;

struct read_retval {
	int status;
	struct {
		u_int bytes_len;
		char *bytes_val;
	} bytes;
};
typedef struct read_retval read_retval;

#define EPNFS 0x331410ff
#define EPNFS_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define EPL_OPEN 1
extern  int * epl_open_1(open_params *, CLIENT *);
extern  int * epl_open_1_svc(open_params *, struct svc_req *);
#define EPL_CREAT 2
extern  int * epl_creat_1(creat_params *, CLIENT *);
extern  int * epl_creat_1_svc(creat_params *, struct svc_req *);
#define EPL_LSEEK 3
extern  int * epl_lseek_1(lseek_params *, CLIENT *);
extern  int * epl_lseek_1_svc(lseek_params *, struct svc_req *);
#define EPL_CLOSE 4
extern  int * epl_close_1(int *, CLIENT *);
extern  int * epl_close_1_svc(int *, struct svc_req *);
#define EPL_WRITE 5
extern  int * epl_write_1(write_params *, CLIENT *);
extern  int * epl_write_1_svc(write_params *, struct svc_req *);
#define EPL_READ 6
extern  read_retval * epl_read_1(read_params *, CLIENT *);
extern  read_retval * epl_read_1_svc(read_params *, struct svc_req *);
extern int epnfs_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define EPL_OPEN 1
extern  int * epl_open_1();
extern  int * epl_open_1_svc();
#define EPL_CREAT 2
extern  int * epl_creat_1();
extern  int * epl_creat_1_svc();
#define EPL_LSEEK 3
extern  int * epl_lseek_1();
extern  int * epl_lseek_1_svc();
#define EPL_CLOSE 4
extern  int * epl_close_1();
extern  int * epl_close_1_svc();
#define EPL_WRITE 5
extern  int * epl_write_1();
extern  int * epl_write_1_svc();
#define EPL_READ 6
extern  read_retval * epl_read_1();
extern  read_retval * epl_read_1_svc();
extern int epnfs_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_open_params (XDR *, open_params*);
extern  bool_t xdr_creat_params (XDR *, creat_params*);
extern  bool_t xdr_lseek_params (XDR *, lseek_params*);
extern  bool_t xdr_write_params (XDR *, write_params*);
extern  bool_t xdr_read_params (XDR *, read_params*);
extern  bool_t xdr_read_retval (XDR *, read_retval*);

#else /* K&R C */
extern bool_t xdr_open_params ();
extern bool_t xdr_creat_params ();
extern bool_t xdr_lseek_params ();
extern bool_t xdr_write_params ();
extern bool_t xdr_read_params ();
extern bool_t xdr_read_retval ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFS_H_RPCGEN */
