/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
epnfs_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		open_params epl_open_1_arg;
		creat_params epl_creat_1_arg;
		lseek_params epl_lseek_1_arg;
		int epl_close_1_arg;
		write_params epl_write_1_arg;
		read_params epl_read_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case EPL_OPEN:
		_xdr_argument = (xdrproc_t) xdr_open_params;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) epl_open_1_svc;
		break;

	case EPL_CREAT:
		_xdr_argument = (xdrproc_t) xdr_creat_params;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) epl_creat_1_svc;
		break;

	case EPL_LSEEK:
		_xdr_argument = (xdrproc_t) xdr_lseek_params;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) epl_lseek_1_svc;
		break;

	case EPL_CLOSE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) epl_close_1_svc;
		break;

	case EPL_WRITE:
		_xdr_argument = (xdrproc_t) xdr_write_params;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) epl_write_1_svc;
		break;

	case EPL_READ:
		_xdr_argument = (xdrproc_t) xdr_read_params;
		_xdr_result = (xdrproc_t) xdr_read_retval;
		local = (char *(*)(char *, struct svc_req *)) epl_read_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (EPNFS, EPNFS_V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, EPNFS, EPNFS_V1, epnfs_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (EPNFS, EPNFS_V1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, EPNFS, EPNFS_V1, epnfs_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (EPNFS, EPNFS_V1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
